// <auto-generated />
using AnimalShelterApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterApi.Migrations
{
    [DbContext(typeof(AnimalShelterApiContext))]
    partial class AnimalShelterApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelterApi.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Name = "Robert",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Name = "Meowsen",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 3,
                            Name = "Arthur",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Name = "Winston",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Name = "Charles",
                            Species = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
